name: Build and push new dev tools image
on:
  push:
    branches:
      - "main"
jobs:
  build-push-dev-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@sethvargo/stack
      - name: Step1
        run: |-
          echo "one"
      - name: Step2
        run: |-
          echo "two"
      - name: Failed?
        if: ${{ failure() }}
        run: |-
          echo "failed :("
      - name: Failed?
        if: ${{ failure() }}
        uses: actions/github-script@9ac08808f993958e9de277fe43a64532a609130e
        with:
          script: |-
              github.rest.issues.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: 'build-push-dev-tools job failed',
                  body: 'Logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}',
                  assignee: 'bharathkkb'
                })
