name: Build and push new dev tools image
on:
  push:
    branches:
      - "main"
jobs:
  build-push-dev-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Step1
        run: |-
          echo "one"
      - name: Step2
        run: |-
          echo "two"
          exit 1
      - name: Failed?
        if: ${{ failure() }}
        run: |-
          echo "failed :("
      - name: Failed?
        if: ${{ failure() }}
        uses: actions/github-script@9ac08808f993958e9de277fe43a64532a609130e
        with:
          script: |-
            # https://docs.github.com/en/rest/reference/issues#create-an-issue--code-samples
              github.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'foo',
                body: 'bar',
                assignee: 'bharathkkb'
            })
